version: '2'

services:    
  db:
    image: 'postgres:14.2'
    container_name: rideschedulerDB
    environment:
      - POSTGRES_DB=ridescheduler
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/a_init.sql
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/b_data.sql