CREATE TABLE bus_stop
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    has_wifi BOOLEAN,
    CONSTRAINT pk_busstop PRIMARY KEY (id)
);

CREATE TABLE bus_line
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_busline PRIMARY KEY (id)
);

CREATE TABLE bus_stop_in_bus_line
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_stop_id       BIGINT                                  NOT NULL,
    bus_line_id       BIGINT                                  NOT NULL,
    time_to_next_stop INT                                     NOT NULL,
    CONSTRAINT pk_busstopinbusline PRIMARY KEY (id)
);

ALTER TABLE bus_stop_in_bus_line
    ADD CONSTRAINT FK_BUSSTOPINBUSLINE_ON_BUS_LINE FOREIGN KEY (bus_line_id) REFERENCES bus_line (id);

ALTER TABLE bus_stop_in_bus_line
    ADD CONSTRAINT FK_BUSSTOPINBUSLINE_ON_BUS_STOP FOREIGN KEY (bus_stop_id) REFERENCES bus_stop (id);

CREATE TABLE schedule
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    busline_id    BIGINT                                  NOT NULL,
    departuretime TIME                               NOT NULL,
    busstop_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_schedule PRIMARY KEY (id)
);

ALTER TABLE schedule
    ADD CONSTRAINT FK_SCHEDULE_ON_BUSLINE FOREIGN KEY (busline_id) REFERENCES bus_line (id);

ALTER TABLE schedule
    ADD CONSTRAINT FK_SCHEDULE_ON_BUSSTOP FOREIGN KEY (busstop_id) REFERENCES bus_stop (id);

